# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoPackageView
                                 A QGIS plugin
 This plugin uses DAWA to geocode Danish addresses with QGIS processing framework
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-07-17
        copyright            : (C) 2023 by AestasGIS
        email                : bvt@aestas.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'AestasGIS'
__date__ = '2023-07-17'
__copyright__ = '(C) 2023 by AestasGIS'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load plugin class from file geopackageview

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geopackageview import GeoPackageViewPlugin
    return GeoPackageViewPlugin()
